### ISSUE TITLE
Compile Failure

### ISSUE THREAD

**Issue by dl748** [plv8/plv8#184]
Running make,

g++  6.1.1
libv8 5.2.258

Error for every .cc file,

error: ‘namespace_’ does not name a type
 #define namespace namespace_

error: ‘using_’ does not name a type
 #define using  using_

error: ‘typename_’ does not name a type
 #define typename  typename_

So I commented them out in every .cc file and the compiling worked for every file.

When linking after compile, failed with

/usr/bin/ld: cannot find -lv8_libplatform
collect2: error: ld returned 1 exit status

Commented out

SHLIB_LINK += -lv8_libplatform
to
## SHLIB_LINK += -lv8_libplatform

Finally compilation was successful.

Also, no "make test" ?

**Comment by JerrySievert** [comment]
thanks for the update.  can you verify that those were part of v8?  i'm not finding them in the plv8 project itself.

if that's the case, it's an upstream issue that we can only track, and not fix directly, which is unfortunate.

**Comment by dl748** [comment]
They are not apart of v8, but apart of plv8, plv8.cc lines 14-18 are an example.  I think its a problem when compiling with G++ instead of CLang.

**Comment by JerrySievert** [comment]
on the `make test`, postgres extensions inherit the postgres testing strategy via `pg_config`, so as noted in the README, the method for testing is:

```
$ make installcheck
```

this runs the regression tests that are in `sql`, and validates them against `expected`.

i am trying to replicate your issue right now, and on fix will add `gcc-6.1` into the test matrix.  previously, we had not been compiling against this target in our ci.

**Comment by JerrySievert** [comment]
i'm not even able to compile that version of v8 - can you tell me what OS you are compiling on, so i can emulate your environment?  i'm running on ubuntu 16.04 against `g++-6.1`.

**Comment by dl748** [comment]
Fedora, I have a package for v8, but I can also compile it from source.

gcc --version
g++ (GCC) 6.1.1 20160510 (Red Hat 6.1.1-2)
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

v8.x86_64                                                   1:5.2.258

ls -l /usr/lib/libv8*

/usr/lib64/libv8_libplatform.a
/usr/lib64/libv8.so -> libv8.so.5
/usr/lib64/libv8.so.5

**Comment by dl748** [comment]
Note: v8 always compiles with CLang not g++, even if it has to download it.

**Comment by JerrySievert** [comment]
we have no real control of the environment that `v8` figures out for itself to compile via.

i'll grab that version of fedora and see what i can do - note that plv8 compiles fine with older versions of g++ (pre 6.0 for sure, have not tried 6.0).

**Comment by dl748** [comment]
Seriously? looking at the master

https://github.com/plv8/plv8/blob/master/plv8.cc

I see lines 14-18 as

`#define delete		delete_
#define namespace	namespace_
#define	typeid		typeid_
#define	typename	typename_
#define	using	using_`

Commenting those lines out, makes it compile at least, but I have to do that for every .cc file in the https://github.com/plv8/plv8/ path

**Comment by dl748** [comment]
Anyway, I still have a precompiled v8 anyway, but the plv8 is what doesn't compile.  At least not without some tweaking of the source files.

**Comment by dl748** [comment]
example

<pre>plv8$ make
sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "2.0.0-dev"/' plv8_config.h.in > plv8_config.h
g++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o plv8.o plv8.cc
plv8.cc:15:19: error: ‘namespace_’ does not name a type
 #define namespace namespace_
                   ^
plv8.cc:15:19: error: ‘namespace_’ does not name a type
 #define namespace namespace_
                   ^
plv8.cc:15:19: error: ‘namespace_’ does not name a type
 #define namespace namespace_
                   ^
plv8.cc:18:16: error: ‘using_’ does not name a type
 #define using  using_
                ^
plv8.cc:18:16: error: ‘using_’ does not name a type
 #define using  using_
                ^
....
....
Makefile:85: recipe for target 'plv8.o' failed
make: *** [plv8.o] Error 1</pre>

**Comment by dl748** [comment]
if I change plv8.cc from
<pre>#define delete    delete_
#define namespace namespace_
#define typeid    typeid_
#define typename  typename_
#define using   using_</pre>

to

<pre>#define delete    delete_
//#define namespace namespace_
#define typeid    typeid_
//#define typename  typename_
//#define using   using_</pre>

i get

<pre>plv8$ make
sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "2.0.0-dev"/' plv8_config.h.in > plv8_config.h
g++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o plv8.o plv8.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o plv8_type.o plv8_type.cc
plv8_type.cc:12:19: error: ‘namespace_’ does not name a type
 #define namespace namespace_
                   ^
...</pre>

So now it compiles into a .o now but now it errors in plv8_type.cc.  If i go through every .cc file and make the same changes, it compiles correctly.

**Comment by JerrySievert** [comment]
that's fine, but i still have to make sure that it compiles on every other platform and compiler, you are the first to report this issue, and it is important to me to not only validate the issue, but validate the fix on every platform/compiler we ship for.

**Comment by dl748** [comment]
No, I understand. I'm just saying you are now having a problem on future g++ versions, and a possible fix for the version.

**Comment by dl748** [comment]
FYI, I had to change 3 files

<pre>plv8.cc
plv8_type.cc
plv8_func.cc</pre>

**Comment by JerrySievert** [comment]
are you installing g++ 6.1 via some other method?

i downloaded and installed fedora 23, did a `dnf update`, but still do not have 6.1 available:

```
[root@localhost jerry]# dnf install gcc-c++.x86_64
Last metadata expiration check: -1 day, 23:19:39 ago on Sat Jun 18 18:40:48 2016.
Dependencies resolved.
================================================================================
 Package               Arch         Version                 Repository     Size
================================================================================
Installing:
 binutils              x86_64       2.25-17.fc23            updates       5.6 M
 cpp                   x86_64       5.3.1-6.fc23            updates       8.3 M
 gcc                   x86_64       5.3.1-6.fc23            updates        19 M
 gcc-c++               x86_64       5.3.1-6.fc23            updates       9.8 M
 glibc-devel           x86_64       2.22-17.fc23            updates       913 k
 glibc-headers         x86_64       2.22-17.fc23            updates       496 k
 isl                   x86_64       0.14-4.fc23             fedora        490 k
 kernel-headers        x86_64       4.5.6-200.fc23          updates       1.0 M
 libmpc                x86_64       1.0.2-4.fc23            fedora         55 k
 libstdc++-devel       x86_64       5.3.1-6.fc23            updates       1.8 M
 mpfr                  x86_64       3.1.3-2.fc23            updates       214 k

Transaction Summary
================================================================================
Install  11 Packages

Total download size: 48 M
Installed size: 132 M
Is this ok [y/N]:
```

**Comment by dl748** [comment]
Yeah sorry, using Fedora 24.
<pre>dnf list "gcc*"
Last metadata expiration check: 2:10:01 ago on Sat Jun 18 19:00:12 2016.
Installed Packages
gcc.x86_64                                                                6.1.1-2.fc24
gcc-c++.x86_64                                                            6.1.1-2.fc24
gcc-gdb-plugin.x86_64                                                     6.1.1-2.fc24
Available Packages
gcc.i686                                                                  6.1.1-2.fc24
gcc-aarch64-linux-gnu.x86_64                                              6.1.1-1.fc24
gcc-alpha-linux-gnu.x86_64                                                6.1.1-1.fc24
gcc-arm-linux-gnu.x86_64                                                  6.1.1-1.fc24</pre>

**Comment by dl748** [comment]
Ubuntu has 6.1.1 as well

**Comment by JerrySievert** [comment]
16.04 does not - it looks like fedora 24 isn't fully supported by vmware fusion, trying to get it up and running as well as possible.

**Comment by JerrySievert** [comment]
i still cannot get `v8` to compile under fedora 24.  i'm really confused, since `v8` is requiring `libtinfo.so.5` which is not supported by fedora 24 (`libtinfo.so.6` is the current ncurses library version supported).

also, the packaged `v8` is `3.14`, which is explicitly not supported by any pl/v8 beyond 1.4.x (there is also a 1.5.x release branch, as well as master, which is 2.0-dev).

```
[root@localhost plv8]# dnf list 'v8*'
Last metadata expiration check: 0:31:58 ago on Sat Jun 18 18:27:02 2016.
Available Packages
v8.i686                            1:3.14.5.10-23.fc24                    fedora
v8.x86_64                          1:3.14.5.10-23.fc24                    fedora
v8-devel.i686                      1:3.14.5.10-23.fc24                    fedora
v8-devel.x86_64                    1:3.14.5.10-23.fc24                    fedora
v8-python.x86_64                   1:3.14.5.10-23.fc24                    fedora
[root@localhost plv8]#
```

**Comment by dl748** [comment]
After those changes

<pre>plv8$ make
sed -e 's/^#undef PLV8_VERSION/#define PLV8_VERSION "2.0.0-dev"/' plv8_config.h.in > plv8_config.h
g++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o plv8.o plv8.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o plv8_type.o plv8_type.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o plv8_func.o plv8_func.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o plv8_param.o plv8_param.cc
echo "extern const unsigned char coffee_script_binary_data[] = {" >coffee-script.cc
(od -txC -v coffee-script.js | \
sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>coffee-script.cc
echo "0x00};" >>coffee-script.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o coffee-script.o coffee-script.cc
echo "extern const unsigned char livescript_binary_data[] = {" >livescript.cc
(od -txC -v livescript.js | \
sed -e "s/^[0-9]*//" -e s"/ \([0-9a-f][0-9a-f]\)/0x\1,/g" -e"\$d" ) >>livescript.cc
echo "0x00};" >>livescript.cc
g++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -fPIC -c -o livescript.o livescript.cc
g++ -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -fpic -shared -o plv8.so plv8.o plv8_type.o plv8_func.o plv8_param.o coffee-script.o livescript.o -L/usr/lib64 -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,--as-needed  -lv8 -lv8_libplatform
sed -e 's/@PLV8_VERSION@/2.0.0-dev/g' plv8.control.common | g++ -E -P -DLANG_plv8 - > plv8.control
sed -e 's/@LANG_NAME@/plv8/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.0.0-dev/g' | g++ -E -P -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -DLANG_plv8 - > plv8--2.0.0-dev.sql
sed -e 's/@PLV8_VERSION@/2.0.0-dev/g' plv8.control.common | g++ -E -P -DLANG_plcoffee - > plcoffee.control
sed -e 's/@LANG_NAME@/plcoffee/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.0.0-dev/g' | g++ -E -P -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -DLANG_plcoffee - > plcoffee--2.0.0-dev.sql
sed -e 's/@PLV8_VERSION@/2.0.0-dev/g' plv8.control.common | g++ -E -P -DLANG_plls - > plls.control
sed -e 's/@LANG_NAME@/plls/g' plv8.sql.common | sed -e 's/@PLV8_VERSION@/2.0.0-dev/g' | g++ -E -P -I. -I./ -I/usr/include/pgsql/server -I/usr/include/pgsql/internal -D_GNU_SOURCE -I/usr/include/libxml2  -DLANG_plls - > plls--2.0.0-dev.sql
plv8$</pre>

So now its compiling fine after those 3 file modifications.

**Comment by dl748** [comment]
There is a package for v8.  But if you want to compile v8, you should use the SRPM, it also includes 2 Red Hat patches.
v8-4.10.91-system_icu.patch to use the system's libicu instead of one built by v8
v8-5.2.197-readdir-fix.patch to fix a readdir problem.

**Comment by JerrySievert** [comment]
i understand what you are saying about the 3 file modifications, but until *i* am able to compile and make the changes, and test against all other platforms with those changes, i cannot correctly fix or prove that the fix is complete.

**Comment by dl748** [comment]
question then, if you make those changes, can you test compile on those other systems and see if the changes still work?

**Comment by JerrySievert** [comment]
the package for v8, as i showed, is `3.14`, even in the SRPM's listed here: https://dl.fedoraproject.org/pub/fedora/linux/updates/testing/24/SRPMS/v/

it is also `3.14`.

also, i am not willing to make a blind change and potentially break the project for everyone.

**Comment by JerrySievert** [comment]
from reading the `g++-6.1` changes log, it appears that they moved from `c++98` to `c++14`, skipping `c++11`, which plv8 and v8 are developed against.

the better check would be to change `-std=c++11` to `-std=gnu++11`, and checking the compile against that.

**Comment by dl748** [comment]
I can easily test that out with my local copy now that know how to get it to compile.

**Comment by JerrySievert** [comment]
please test against the repo in its original state, not with the changes you made

**Comment by dl748** [comment]
well unless there is a change to the repo, the same thing will fail.  I undid all my coding changes(all they were, were commented out lines of code), and changed Makefile to use -std=gnu++11

**Comment by JerrySievert** [comment]
not necessarily, the `-std=gnu++11` changes the behavior of the compiler - until g++ 6, g++ used the c++ 98 standard.

plv8 and v8 have been developed against the c++ 11 standard.  g++ 6 changed to use the c++ 14 standard.

the change i asked you to try was to ask g++ to use the c++ 11 standard.

**Comment by dl748** [comment]
I did, see above, the g++ command i pasted has -std=gnu++11 as the parameter when compiling

**Comment by JerrySievert** [comment]
wow.  i applaud `redhat` for getting `fedora` compiling with a modern compiler.  but, wow, dealing with it has been a bit of a mess.

i managed to finally get `v8` compiling, and am having to compile `postgres` from source in order to get anything else that relies it to compile.

after about 16 hours, i'm getting closer to be able to run tests - most likely no resolution until this weekend, as i will be traveling for work.

**Comment by JerrySievert** [comment]
also, FYI - all tests are failing on `fedora` - this is going to take a lot more than commenting out lines to fix.

**Comment by dl748** [comment]
You can get PostgreSQL directly from the source.

http://yum.postgresql.org/

This makes it a lot faster.

**Comment by dl748** [comment]
How do you run tests for plv8?  The standard "make test" doesn't work for it.

**Comment by JerrySievert** [comment]
as noted above, PL/v8 is an extension for Postgres, and thus uses the same method of running tests:

```
$ make installcheck
```

**Comment by JerrySievert** [comment]
commenting out those lines for fedora *does not work*.  the tests do not pass, as the version of `v8` that fedora ships does not have `libv8_platform`, which is a requirement.  in addition, i am still unable to compile `v8` from source.

i am happy to revisit this once fedora 24 is out of beta, but for now, there are just too many issues with the platform to even get a working version of *anything*.

considering that the version of postgres that it shipped with wouldn't work with extensions, and v8 itself won't even compile, there are a lot of other issues with that platform that need to be solved before tackling this again.

**Comment by ChristophBerg** [comment]
Hi,
the g++ 6 problem is now visible on Debian/experimental as well: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831190

```
g++ -Wall -O2 -std=c++11 -fno-rtti  -I. -I./ -I/usr/include/postgresql/9.5/server -I/usr/include/postgresql/internal -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include/tcl8.6 -fPIC -c -o plv8.o plv8.cc
In file included from /usr/include/c++/6/math.h:36:0,
                 from /usr/include/postgresql/9.5/server/datatype/timestamp.h:18,
                 from /usr/include/postgresql/9.5/server/utils/timestamp.h:16,
                 from /usr/include/postgresql/9.5/server/utils/datetime.h:20,
                 from /usr/include/postgresql/9.5/server/access/xact.h:22,
                 from plv8.cc:21:
/usr/include/c++/6/cmath:79:1: error: ‘namespace_’ does not name a type
 namespace std _GLIBCXX_VISIBILITY(default)
 ^~~~~~~~~~
...
```

g++ (Debian 6.1.1-9) 6.1.1 20160705
plv8 1.4.8
libv8-3.14.5            3.14.5.8-10

**Comment by JerrySievert** [comment]
thanks @ChristophBerg - that's a platform i can test against :)

i'll take a look soon and get a backport out for debian as well.

**Comment by ChristophBerg** [comment]
(In the meantime, gcc 6 is the default compiler for Debian/unstable, and plv8 will be removed from testing until there is a fix.)

**Comment by ChristophBerg** [comment]
Hi,
this issue is holding back the completion of moving Debian unstable to PostgreSQL 9.6, i.e. we'd need to be able to actually compile plv8 for 9.6 so we can remove the existing postgresql-9.5-plv8 package.
Is there anything I can do to help?

**Comment by JerrySievert** [comment]
If you want to remove the offending lines and try to send against Travis, that would be a huge help.

**Comment by ChristophBerg** [comment]
Ok I'll see what I can do.

**Comment by JerrySievert** [comment]
all branches up to date, closing.
