### PR TITLE
Support msvc

### PR DESCRIPTION
**Pull request by kjunichi**
Hello!

I try following:

> Windows:
> TODO - PL/v8 supports Windows. A Pull Request for installation steps is greatly appreciated

Unfortunately I don't know CMake, V8, windows well.
So please be careful to use this patch.

## Step 1.

You have to patch PostgreSQL's header file.
generic-msvc.h.patch is a patch for this.

## Step2

```shell
$ bootstrap.bat
$ cmake . -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX="C:\Program Files\PostgreSQL\9.6" -DPOSTGRESQL_VERSION=9.6
$ cmake --build . --config Release --target Package
```

Unzip it, and copy to PostgreSQL directories.

### CODE REVIEW

**Comment by kjunichi** [comment]
I've tried it, and I build my own V8.
But I couldn't success with it.
It seems my build version V8 looks for snapshot_blob.bin,natives_blob.bin.
I tried to put it under PostgreSQL's path,but I did't find correct path.
so, I  use nuget version V8,it dit not need snapshot_blob.bin,natives_blob.bin.

**Comment by JerrySievert** [comment]
thanks!  I've been trying to work with the azure team in getting v8 compiled on windows, this helps.

**Comment by JerrySievert** [comment]
I'll try to do a full review of your changes tomorrow - I will likely ask for a couple of small changes, but will let you know.

**Comment by mmicr001** [comment]
Hi! I appreciate all the work that you guys are putting into this. 

I am attempting to install plv8 on Windows 10 64-bit with VS2015. 
I have been following all the instructions from @kjunichi  post -> [https://dev.to/kjunichi/how-to-build-plv8-on-windows-4d](url) up until the last step.  
- Firstly, I was unable to apply the patch that @kjunichi  mentions in step 1 (on this page) because even though there is a generic_msvc.h.patch file, there is no generic_msvc.h file in the repo that I cloned.
- Secondly, when I run the last step from the post:
`$ cmake --build . --config Release --target Package`
 I get a fatal error because the compiler cannot find "postgres.h" which is not in the directory.

`c:\postgres\plv8\plv8.h(19): fatal error C1083: Cannot open include file: 'postgres.
h': No such file or directory [C:\postgres\plv8\libplv8.vcxproj]
  plv8_func.cc
c:\postgres\plv8\plv8.h(19): fatal error C1083: Cannot open include file: 'postgres.
h': No such file or directory [C:\postgres\plv8\libplv8.vcxproj]
  plv8_param.cc
c:\postgres\plv8\plv8_param.h(5): fatal error C1083: Cannot open include file: 'post
gres.h': No such file or directory [C:\postgres\plv8\libplv8.vcxproj]
  plv8_type.cc
c:\postgres\plv8\plv8.h(19): fatal error C1083: Cannot open include file: 'postgres.
h': No such file or directory [C:\postgres\plv8\libplv8.vcxproj]`

I am not sure if this is related to the patch or if there is something I should add to my system PATH.

What am I missing/messing up?

**Comment by JerrySievert** [comment]
I can't speak for the work that @kjunichi did, but I can tell you that in order to compile, you'll need the source for postgres installed, that is why it cannot file `postgres.h`

**Comment by kjunichi** [comment]
you don't have to install Postgres's soruce.
you only have to install PostgreSQL 9.6 from official site.
Then you get postgres.h where located at C:\Program Files\PostgreSQL\9.6\include\server.

**Comment by JerrySievert** [comment]
@kjunichi - which installer did you use that you didn't need to install source?  I used EnterpriseDB (the default installer), and it is missing the `lib/pgxs` directory, which is needed for building.

**Comment by kjunichi** [comment]
@JerrySievert Hi, pgxs does not work on Windows, so this patch does not use lib/pgxs.
Yesterday I confirmed this patch worked using MS's virtual machine.

**Comment by mmicr001** [comment]
@JerrySievert I have installed postgres already. I had a different path to the postgres directories than @kjunichi which seemed to be the main source of my problems.

I was able to overcome my previous errors by going into the **CMakeCache.txt** and changing the  **POSTGRESQL_DIR:PATH** to the correct postgres directrory.  I similarly had to apply the same change to the DCMAKE_INSTALL_PREFIX variable in the command: 
`$ cmake . -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX="C:\Program Files\PostgreSQL\9.6" -DPOSTGRESQL_VERSION=9.6
`

After following the updated post by @kjunichi, plv8 was built successfully with 48 warning and 0 errors.
Thank you guys @JerrySievert and @kjunichi  for all the help and quick responses. hopefully all works well

**Comment by JerrySievert** [comment]
after spending several days in hell (windows), I'm still pretty concerned about this pull request - I'm not opposed to adding direct support, and am ok with rearranging everything to not be confusing to the bulk of users and those using pgxn, but am concerned about nuget.

specifically:

* there is no documentation for those unfamiliar with nuget itself (it is a separate command line download, and requires configuration not mentioned for repositories specific to v8)
* nuget's v8 version is below the absolute minimum for accepting a PR at this point.  as of the spectre/meltdown issues, the absolute minimum version of v8 that deal with this is 6.4.388.14, and most, including plv8 and node, have moved to 6.4.388.40 to better mitigate the issues.  the highest that nuget has gone is 6.4.388.11, in 141.

once those issues are addressed, I can move forward in accepting the pr.

**Comment by JerrySievert** [comment]
nuget install:

```
PM> Install-Package v8-v141_xp-x64 -Version 6.4.388.11
Install-Package : The current environment doesn't have a solution open.
At line:1 char:1
+ Install-Package v8-v141_xp-x64 -Version 6.4.388.11
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetNoActiveSolution,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 ```

**Comment by JerrySievert** [comment]
also @kjunichi have you tried this with vs2017?  I'm getting strange issues dealing with overloaded functions, that quite frankly don't make any sense:

```
 'v8::Date::New': no overloaded function takes 1 arguments
```

where 2 arguments are being passed in, but the compiler is incorrectly identifying it as 1 argument.

**Comment by JerrySievert** [comment]
also found that postgres 10 has other compilation errors in `postgres.h` for msvc 2017, that I commented past.

now getting: `  v8.lib(v8.dll) : fatal error LNK1112: module machine type 'x64' conflicts with target machine type 'x86' [C:\msys64\t
mp\plv8\libplv8.vcxproj]`

both x64 versions of postgres and v8 are installed, and system information shows x64 across the board.

is anything easy in windows? or is all development this painful?

**Comment by JerrySievert** [comment]
a couple of additional issues:

* this will not work with current master, due to ABI changes in v8, `5.8` does not have the same method signatures, and msvc considers `override` to be an error
* `6.4` build from nuget has changed enough that it will not link against plv8 with the current build scripts

these issues will need to be fixed as well.

**Comment by JerrySievert** [comment]
@kjunichi it also does not work with `master`, nor the current (`2.3.0`) release, unfortunately.

**Comment by kjunichi** [comment]
Hello!,I'm updating this patch, and I success to run plv8(master branch) with V8 6.4.
In this time you have to build v8 in local with VS 2017(Community ver.).
bootstrap.bat needs some updating.

I'll update this patch soon in April.

**Comment by JerrySievert** [comment]
fantastic! thank you! I look forward to the update!

**Comment by kjunichi** [comment]
Hi, @pashcovich .

You have to following files to C:\Program Files\PostgreSQL\9.6\share\extension.

- plcoffee.control
- plcoffee--2.3.1.sql
- plls.control
- plls--2.3.1.sql

you'll get these files by building plv8 from source on Unix platfom,or macOS.
or
edit from plv8.sql.common,plv8.control.common files.

next time,I'll update this patch.

**Comment by kjunichi** [comment]
Now, I've updated this patch for 2.3.1

**Comment by JerrySievert** [comment]
I've created an issue on nuget-v8: https://github.com/pmed/v8-nuget/issues/7

**Comment by kjunichi** [comment]
I have a question:

nuget's v8 has compiled option with v8_use_external_startup_data=true.
This causes crash with plv8.(I've already  tired this.)

Will you add

something like:

```c
v8::V8::InitializeExternalStartupData(argv[0]);
```

to plv8's source code?

Anyway thanks for checking my pull request and support.

**Comment by JerrySievert** [comment]
on plv8.cc line 341:

```
#if V8_MAJOR_VERSION == 4 && V8_MINOR_VERSION >= 6
	V8::InitializeExternalStartupData("plv8");
#endif```

can be changed to:

```
#if (V8_MAJOR_VERSION == 4 && V8_MINOR_VERSION >= 6) || V8_MAJOR_VERSION >= 5
	V8::InitializeExternalStartupData("plv8");
#endif
```

check to make sure that it works for you, and if it does, add it into your PR.

**Comment by JerrySievert** [comment]
I went ahead and added the V8_MAJOR_VERSION change, since I was cutting a release anyways - pull from master and you should see it.

**Comment by kjunichi** [comment]
@JerrySievert 
I try this.
but I have no luck.
Do you know where put to snapshot_blob.bin?

I've just got this error:

```
#

# Fatal error in ../../../../src/api.cc, line 8612

# Check failed: (isolate->snapshot_blob()) == nullptr.

#



==== C stack trace ===============================



	v8::base::time_internal::TimeBase<v8::base::TimeTicks>::ToInternalValue [0x00007FFCDAC612A1+63079]

	v8::platform::DefaultForegroundTaskRunner::DefaultForegroundTaskRunner [0x00007FFCE72E63D2+19593]

	v8::base::time_internal::TimeBase<v8::base::TimeTicks>::ToInternalValue [0x00007FFCDAC5C3D8+42910]

	v8::internal::Builtins::builtin_handle [0x00007FFC94BBECCA+495851]

	PG_init [0x00007FFCDA2169AE+686]

	RestoreLibraryState [0x00000001403AC2F7+903]

	load_external_function [0x00000001403ABCF4+52]

	fmgr_c_validator [0x00000001400B2B69+313]

	OidFunctionCall1Coll [0x00000001403AE066+118]

	ProcedureCreate [0x00000001400B2767+4679]

	CreateFunction [0x00000001400E60D7+1751]

	CommandIsReadOnly [0x00000001402A3C91+2401]

	standard_ProcessUtility [0x00000001402A2078+2216]

	ProcessUtility [0x00000001402A17C1+49]

	pg_extension_config_dump [0x00000001400E18BA+8314]

	pg_extension_config_dump [0x00000001400E1CA4+9316]

	pg_extension_config_dump [0x00000001400E2ABA+12922]

	CreateExtension [0x00000001400DDC98+312]

	CommandIsReadOnly [0x00000001402A3AE5+1973]

	standard_ProcessUtility [0x00000001402A2078+2216]

	ProcessUtility [0x00000001402A17C1+49]

	PortalRunFetch [0x00000001402A0F1A+2234]

	PortalRunFetch [0x00000001402A10EB+2699]

	PortalRun [0x00000001402A0451+401]

	get_stats_option_name [0x000000014029E0C6+5222]

	PostgresMain [0x000000014029C2B4+1588]

	ShmemBackendArrayAllocation [0x000000014023368A+10810]

	SubPostmasterMain [0x0000000140230AA2+546]

	main [0x000000014016EB30+1152]

	pgwin32_popen [0x00000001403F457F+4927]

	BaseThreadInitThunk [0x00007FFCF39F1FE4+20]

	RtlUserThreadStart [0x00007FFCF4C5F061+33]
```


I tried follwing locate:

- C:\Program Files\PostgreSQL\9.6\bin\plv8
- C:\Program Files\PostgreSQL\9.6\lib\plv8

**Comment by JerrySievert** [comment]
that's the thing - we can include the call, but it has to be a `NOP` - plv8 is a trusted extension, and being able to alter what the extension has access to, and how it behaves, for each session is a big no-no.  previously, not having the snapshot would fallback to non-external behavior (which is why the call is there in the first place).

**Comment by JerrySievert** [comment]
question: did nuget change how they built v8?  since it seemed to be working on the older version.

**Comment by kjunichi** [comment]
nuget does not specify option of v8_use_external_startup_data .

but plv8's v8 option is:
```
V8_OPTIONS = is_component_build=false v8_static_library=true v8_use_snapshot=true v8_use_external_startup_data=false
```

```
v8_use_external_startup_data=false
```

I think this parameter to avoid the problem that I've got on Nuget's v8.

**Comment by JerrySievert** [comment]
correct, as noted, plv8 cannot directly support loading of a snapshot.

**Comment by kjunichi** [comment]
To be clarify,current this pull request build own v8.you don't have to use nuget.

**Comment by JerrySievert** [comment]
great - I will attempt to build again tomorrow in windows.  this is for v8 version 6.4.388.14 and above, correct?

**Comment by kjunichi** [comment]
now it uses 6.4.388.40.it same version of master branch.

**Comment by davidbeauchamp** [comment]
I was able to build this PR last night with 6.4.388.40 and with plv8 2.3.2 merged in, for x64 and ia32. The CMake files are hardcoded to look for x64 but does build fine when edited for ia32. Some notes:

In order to build for PostgreSQL 9.3 and 9.4 on both architectures I had to comment out a few `__attribute()__` calls, in datetime.h, lock.h and stringinfo.h. It looks like a that was refactored for 9.5 and above but I didn't feel it was worth trying to backport those changes. Otherwise the rest builds as described and calls to `plv8_version()` in all return `2.3.2`.

For building ia32/x86 use this to generate the build files: 
`cmake . -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX="C:\Program Files\PostgreSQL\9.6" -DPOSTGRESQL_VERSION=9.6`

In bootstrap.bat you also need to change `x64.release` to `ia32.release`

**Comment by JerrySievert** [comment]
huzzah, got it to build, and I'll be damned but it works!

great work @kjunichi!

I'm going to merge it locally into my fork, and make a few changes to the build process and add some documentation.

I'll have you run through it on my fork before I open up the new PR and merge.

I'll leave this issue open until it's all said and done.

**Comment by JerrySievert** [comment]
see #272

**Comment by JerrySievert** [comment]
closing, was merged in #272
